version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./cs:/cs
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - cs-network
    php:
        image: php:fpm
        volumes:
            - ./cs:/cs
        networks:
            - cs-network

networks:
    cs-network:
        driver: bridge
